site_name: DevOps Documentation
site_url: https://gitbex.github.io/mkdocs/devops/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - drawio:
      format: svg
      sources: '*.drawio'



markdown_extensions:
  - admonition
  - pymdownx.superfences
  - attr_list

nav:
  - "‚Üê Back to Main": https://gitbex.github.io/mkdocs/
  - Home: index.md
  - Runbooks:
      - Overview: runbooks/index.md
      - MFA create from console: runbooks/mfa-console.md
      - MFA CLI usage: runbooks/mfa-cli.md
      - CloudWatch create: runbooks/cw.md
      - ECS troubleshooting: runbooks/ecs-logs.md
      - ECS scaling: runbooks/ecs-scaling.md
  - Infrastructure:
      - Architecture overview: infrastructure/diagram.md
      # - AWS: infrastructure/aws.md
      # - Kubernetes: infrastructure/kubernetes.md
  - CI/CD:
      - Overview: ci-cd/index.md
      - GitHub Actions: ci-cd/github-actions.md
      - Jenkins: ci-cd/jenkins.md
  - Monitoring:
      - Overview: monitoring/index.md
      - CloudWatch: monitoring/cloudwatch.md
      - Grafana: monitoring/grafana.md
  - Onboarding:
      - New Member Guide: onboarding/index.md
      - Tools Setup: onboarding/tools.md
      - Access Requests: onboarding/access.md

extra:
  social:
    - icon: fontawesome/solid/house
      link: https://gitbex.github.io/mkdocs/
      name: Back to Main Docs

repo_name: datatruck/tech-docs
repo_url: https://github.com/datatruck/tech-docs